name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: foundryvtt-runner
        registry: ghcr.io
        addLatest: true
        dockerfile: Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
